apiVersion: apps/v1
kind: Deployment
metadata:
  name: od-v1
spec:
  replicas: 5
  selector:
    matchLabels:
      app: od
      version: v1
  template:
    metadata:
      labels:
        app: od
        version: v1
        env: production
    spec:
      containers:
        # Here is the image of the container
        - name: od
          image: gcr.io/instructor-partition/od-fasterrcnn
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
